require("dotenv").config();
const express = require("express");
const mahasiswaRoutes = require("./routes/mahasiswaRoutes");
const prodiRoutes = require("./routes/prodiRoutes");
const matakuliahRoutes = require("./routes/matakuliahRoutes");
const krsRoutes = require("./routes/krsRoutes");
const kartuRoutes = require("./routes/kartuRoutes");
const jurusanRoutes = require("./routes/jurusanRoutes");
const dosenRoutes = require("./routes/dosenRoutes");
const pengampuMatakuliahRoutes = require("./routes/pengampuMatakuliahRoutes");
const penelitianRoutes = require("./routes/penelitianRoutes");
const pengabdianRoutes = require("./routes/pengabdianRoutes");
const publikasiJurnalRoutes = require("./routes/publikasiJurnalRoutes");
const bukuAjarRoutes = require("./routes/bukuAjarRoutes");
const bahanAjarRoutes = require("./routes/bahanAjarRoutes");
const hkiRoutes = require("./routes/hkiRoutes");
const laboratoriumRoutes = require("./routes/laboratoriumRoutes");
const tendikRoutes = require("./routes/tendikRoutes");
const jadwalKuliahRoutes = require("./routes/jadwalKuliahRoutes");
const khsRoutes = require("./routes/khsRoutes");
const { notFound, errorHandler } = require("./middleware/errorHandler");
const { requireAdminForMutations } = require("./middleware/requireAdminForMutations");
const app = express();
app.use(express.json());
app.use(express.urlencoded({ extended: true }));
app.use(requireAdminForMutations);
app.get("/", (req, res) => {
  res.send("API Sistem Akademik berjalan");
});
app.use("/mahasiswa", mahasiswaRoutes);
app.use("/prodi", prodiRoutes);
app.use("/matakuliah", matakuliahRoutes);
app.use("/krs", krsRoutes);
app.use("/kartu", kartuRoutes);
app.use("/jurusan", jurusanRoutes);
app.use("/dosen", dosenRoutes);
app.use("/pengampu-matakuliah", pengampuMatakuliahRoutes);
app.use("/penelitian", penelitianRoutes);
app.use("/pengabdian", pengabdianRoutes);
app.use("/publikasi-jurnal", publikasiJurnalRoutes);
app.use("/bahan-ajar", bahanAjarRoutes);
app.use("/buku-ajar", bukuAjarRoutes);
app.use("/hki", hkiRoutes);
app.use("/laboratorium", laboratoriumRoutes);
app.use("/tendik", tendikRoutes);
app.use("/jadwal-kuliah", jadwalKuliahRoutes);
app.use("/khs", khsRoutes);

app.use(notFound);
app.use(errorHandler);

module.exports = app;
